name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - run: dotnet build Stately

      - uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Stately/Stately.csproj
          VERSION_FILE_PATH: .props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}