name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build & pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          # source-url: https://nuget.pkg.github.com/brookesb91/index.json
        # env:
        #   NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}

      - run: dotnet build Stately
      - run: dotnet pack --configuration Release Stately
      - name: publish
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
        run: dotnet nuget push -s https://www.nuget.org/api/v3/package -k $NUGET_AUTH_TOKEN ./Stately/bin/Release/*.nupkg
      # - run: dotnet nuget push Stately/bin/Release/*.nupkg